### ISSUE TITLE
[Compat] Mixin conflict with I'm Fast

### ISSUE THREAD

**Issue by Partonetrain** [mortuusars/Horseman#26]
`fix_horse_moved_wrongly` can be disabled in the config, but the mixin still tries to apply.
It would be nice if both mods worked together, since Horseman doesn't affect the "player moved to quickly" problem.

Horseman mixin: https://github.com/mortuusars/Horseman/blob/1.21.1/neoforge/src/main/java/io/github/mortuusars/horseman/neoforge/mixin/fix_moved_wrongly/ServerGamePacketListenerImplMixin.java#L22

I'm Fast mixin: https://github.com/Gabriel-Hiss/Im-Fast/blob/1.21.1-Forge/src/main/java/com/biel/mod/mixin/VelocityMixin.java#L38

```
[30Apr2025 16:34:36.291] [modloading-worker-0/ERROR] [net.neoforged.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: platform, class com.blackgear.platform.neoforge.PlatformForge
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-11.0.4.jar:11.0.4+main.d2e20e43]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:94) ~[modlauncher-11.0.4.jar:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-11.0.4.jar:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:57) ~[modlauncher-11.0.4.jar:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:190) ~[securejarhandler-3.0.8.jar:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$20(ModuleClassLoader.java:298) ~[securejarhandler-3.0.8.jar:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:311) ~[securejarhandler-3.0.8.jar:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:298) ~[securejarhandler-3.0.8.jar:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:214) ~[securejarhandler-3.0.8.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
	at java.base/java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:?]
	at java.base/java.lang.Class.privateGetPublicMethods(Unknown Source) ~[?:?]
	at java.base/java.lang.Class.getMethods(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Proxy$ProxyBuilder.referencedTypes(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Proxy$ProxyBuilder.<init>(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Proxy$ProxyBuilder.<init>(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Proxy.lambda$getProxyConstructor$0(Unknown Source) ~[?:?]
	at java.base/jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(Unknown Source) ~[?:?]
	at java.base/jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Proxy.getProxyConstructor(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Proxy.newProxyInstance(Unknown Source) ~[?:?]
	at TRANSFORMER/platform@1.2.8/com.blackgear.platform.core.util.event.Event.lambda$create$1(Event.java:23) ~[platform-neoforge-1.21.1-1.2.8.jar%23603!/:?]
	at TRANSFORMER/platform@1.2.8/com.blackgear.platform.core.util.event.SimpleEvent.<init>(SimpleEvent.java:19) ~[platform-neoforge-1.21.1-1.2.8.jar%23603!/:?]
	at TRANSFORMER/platform@1.2.8/com.blackgear.platform.core.util.event.Event.create(Event.java:19) ~[platform-neoforge-1.21.1-1.2.8.jar%23603!/:?]
	at TRANSFORMER/platform@1.2.8/com.blackgear.platform.core.util.event.Event.create(Event.java:23) ~[platform-neoforge-1.21.1-1.2.8.jar%23603!/:?]
	at TRANSFORMER/platform@1.2.8/com.blackgear.platform.core.networking.ServerListenerEvents.<clinit>(ServerListenerEvents.java:8) ~[platform-neoforge-1.21.1-1.2.8.jar%23603!/:?]
	at TRANSFORMER/platform@1.2.8/com.blackgear.platform.core.util.config.ConfigLoader.bootstrap(ConfigLoader.java:33) ~[platform-neoforge-1.21.1-1.2.8.jar%23603!/:?]
	at TRANSFORMER/platform@1.2.8/com.blackgear.platform.Platform.bootstrap(Platform.java:24) ~[platform-neoforge-1.21.1-1.2.8.jar%23603!/:?]
	at TRANSFORMER/platform@1.2.8/com.blackgear.platform.neoforge.PlatformForge.<init>(PlatformForge.java:10) ~[platform-neoforge-1.21.1-1.2.8.jar%23603!/:?]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
	at MC-BOOTSTRAP/fml_loader@4.0.38/net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:115) ~[loader-4.0.38.jar%23105!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.38/net.neoforged.fml.ModLoader.lambda$constructMods$3(ModLoader.java:153) ~[loader-4.0.38.jar%23105!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.38/net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$7(ModLoader.java:231) ~[loader-4.0.38.jar%23105!/:4.0]
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) [?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) [?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source) [?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method imfast_VehicleMovedWrong(D)D in imfast.mixins.json:VelocityMixin from mod imfast failed injection check, (0/1) succeeded. Scanned 0 target(s). No refMap loaded.
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:531) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1490) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:752) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:330) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	... 47 more
```

**Comment by mortuusars** [comment]
Fixed in 1.3.4.

**Comment by HatTrkPatrk** [comment]
This is unfortunately still happening. I don't know if compatibility with I'm Fast specifically was resolved (I'm not using that mod) but Horseman's mixin inherently conflicts with any mod that applies the same patch and results in the server failing to start with a mixin error. Even with `fix_horse_moved_wrongly = false` set in the config file, Horseman still applies the mixin itself:
https://github.com/mortuusars/Horseman/blob/1.21.1/fabric/src/main/java/io/github/mortuusars/horseman/fabric/mixin/fix_moved_wrongly/ServerGPLImplMixin.java

As a temporary fix for my server, I removed `ServerGamePacketListenerImplMixin` from horseman-fabric.mixins.json in the JAR and the server starts.

I'm on Fabric 1.21.1 if that matters. P.S. love the ASCII art lol. And that's a very weird issue. Honestly my experience with Fabric seems to be going downhill lately in some ways.

**Comment by mortuusars** [comment]
@HatTrkPatrk 
It might be because I seem to forgot to change mixin name in `HorsemanFabricMixinPlugin` (where it disables it when imfast is loaded) from "ServerGamePacketListenerImplMixin" to "ServerGPLImplMixin". 
Tried testing it - for some reason imfast doesn't even load as a mod, even though it is present in the folder, and prism shows it: 

<img width="440" height="157" alt="Image" src="https://github.com/user-attachments/assets/e6a70aa8-19b6-4f32-8cbb-544465ac810b" />

But then the mod doesn't load, and is missing further down in the log.

---

The problem with this mixin is that it will crash with any other mod that modifies same code (at least I haven't found a way to work around that). The only way to disable it - is to manually check if some other conflicting mod is loading, which I do here: https://github.com/mortuusars/Horseman/blob/1.21.1/fabric/src/main/java/io/github/mortuusars/horseman/fabric/HorsemanFabricMixinPlugin.java

Disabling it in the config will not work, as config is loaded later then mixins are applied. Setting `fix_horse_moved_wrongly = false` will still use the mixin, it will just return the same value.

**Comment by HatTrkPatrk** [comment]
If that's the case, then could either (a) remove this option from Horseman, as it's implemented in other mods that do more than just that one fix for specifically horses and can simply be installed alongside Horseman, or (b) implement the full range of movement check bypasses that the other mods implement?

**Comment by mortuusars** [comment]
I think just turning of the mixin when conflicting mod is present, as I'm doing currently, is still the best option. 
There are not that many mods that conflict with this, and it's not that hard to add it to the list and make a release.

I'll fix the mixin name and release a fixed version. Let me know if it's working as I cannot test it myself.

**Comment by HatTrkPatrk** [comment]
Unfortunately it's still happening for me with the new Horseman version. I figured it would, since I'm not specifically using "I'm Fast" myself, it's another mod that applies similar mixins.

I still need to remove the mixin entry from the `horseman-fabric.mixins.json` array for the server to work.

**Comment by mortuusars** [comment]
@HatTrkPatrk which mod you're using?

**Comment by HatTrkPatrk** [comment]
> [@HatTrkPatrk](https://github.com/HatTrkPatrk) which mod you're using?

I wrote one myself. This isn't really the point. ANY mod that does the same mixin will cause the same problem, and creating single-target exceptions for them all is rather pointless.
